server:
  port: 809

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    registerWithEureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://192.168.241.131:8761/eureka/

spring:
  application:
    name: uselist



